### PR TITLE
Fixing example -h -> --host

### PR DESCRIPTION
**Pull request by nilportugues**
Great project!

I just noticed the example had a tiny bug. You're using the help command instead of the host command when choosing the Amazon website.

### CODE REVIEW

**Comment by drawrowfly** [comment]
Glad you like it :)
Capital -H is used to set host

**Comment by nilportugues** [comment]
I did, I was just contributing to your documentation :)

**Comment by drawrowfly** [comment]
oh my bad

**Comment by drawrowfly** [comment]
thank you )

**Pull request merged**
